// <auto-generated />
namespace moviemall.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Exercise5_littleChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exercise5_littleChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060221577_Exercise5_littleChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
